#!/usr/bin/perl -w

use strict;

my $script_dir;
BEGIN { ($script_dir = $0) =~ s/\/migrate//; }
use lib ($script_dir);

use Log;
use Migrate::Common;
use Migrate::Help;
use DBI;

$Getopt::Std::STANDARD_HELP_VERSION = 1;
our $VERSION = '0.0.1';

main();

sub main
{
    my $dbh = Dbh::getDBH();
    Migrate::Common::initMigrations($dbh);

    Migrate::Common::execute();
}

sub HELP_MESSAGE
{
    my $fh = shift;
    Migrate::Help::show($fh);
}

sub VERSION_MESSAGE
{
    my $fh = shift;
    print($fh "Migrate v$VERSION\n");
}
