#!/usr/bin/perl -w

use strict;

my $script_dir;
BEGIN { ($script_dir = $0) =~ s/[\/\\:]?migrate$//; }
use lib ("$script_dir/lib");

use feature 'say';

use Migrate;
use Migrate::Help;

$Getopt::Std::STANDARD_HELP_VERSION = 1;
our $VERSION = '0.001';

main();

sub main { Migrate::execute() }

sub HELP_MESSAGE { Migrate::Help::show(shift) }
sub VERSION_MESSAGE { my $fh = shift; say($fh "Migrate v$VERSION\n") }
